CC = gcc
CFLAGS = -Wall -g

TARGET = webSearch
OBJS = webSearch.o webUtil.o indexPage.o trieUtil.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET) -lm

%.o: %.c %.h
	$(CC) $(CFLAGS) -c $< -o $@

webSearch.o: webSearch.c webUtil.h indexPage.h

clean:
	rm -f *.o $(TARGET)
